const tintColorLight = "#2f95dc";
const tintColorDark = "#fff";

export default {
  light: {
    text: '#000',
    background: '#fafafa',
    iconColor:'#000',
    tint: tintColorLight,
    buttonText:'#fafafa',
    tabIconDefault: '#ccc',
    linkButton:'#2f95dc',
    tabIconSelected: tintColorLight,
    mainColor: '#e74d36',
    darkModeBackground: '#fff',
    heartColor: '#cf1322',
    borderColor: '#d9d9d9',
    placeholderTextColor: '#a3a3a3',
    starColor: '#fadb14',
    badgeText: '#fff',
    genelBackground: '#fafafa',
    successTextColor: '#50c594',
    maincolortSearchBar: '#e74d36',
    grayText:'#a3a3a3',
    whiteBackgroundCardColor:'#fff',
    inputColor:'#f5f5f4',
  },
  dark: {
    text: '#fff',
    background: '#000',
    iconColor:'#fff',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    buttonText:'#fafafa',
    tabIconSelected: tintColorLight,
    mainColor: '#e74d36',
    linkButton:'#2f95dc',
    darkModeBackground: '#141414',
    heartColor: '#cf1322',
    borderColor: '#434343',
    placeholderTextColor: '#434343',
    starColor: '#fadb14',
    badgeText: '#fff',
    successTextColor: '#50c594',
    maincolortSearchBar: '#fff',
    grayText:'#FFF',
    whiteBackgroundCardColor:'#141414',
    inputColor:'#262626',
  },
};
